typography_spectrum: 0.964059861144051
color:
  brandColors:
    - '#ff3c00'
    - '#ff0000'
    - '#ff3300'
    - '#ff2b00'
    - '#ff1c00'
  brandStrength: 1
  lightness: 0.5154593582265079
  saturation: 0.020738796796649694
  rhythmicContrast: 0.06535223592072725
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6020916081033647
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Lonetour '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Lonetour Press
description: from art to books
purpose: []
